version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: bank_app
    environment:
      MYSQL_DATABASE: bankappdb
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: Test@123
    ports: 
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      timeout: 5s
      retries: 10
      start_period: 10s
  

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/"]
      interval: 3s
      timeout: 5s
      retries: 10
      start_period: 10s


  bank-app:
    build: .
    container_name: bankapp
    ports:
      - "80:8080"
    depends_on:
      mysql:
        condition: service_healthy
      ollama:
        condition: service_healthy
    
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: bankappdb
      MYSQL_USER: root
      MYSQL_PASSWORD: Test@123
      OLLAMA_URL: http://ollama:11434